# Numpy 套件


In [34]:
a = [1,2,3,4,5]
print(a*3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


### numpy套件的ndarray型態,提供element-wise的操作

In [35]:
import numpy as np
b = np.array([1,2,3,4,5])
print(b*4)

[ 4  8 12 16 20]


In [36]:
print(type(b))
print(b.ndim) #ndarray的維度
print(b.shape) #ndarray的shape
print(b.dtype) #ndarray的資料型態

<class 'numpy.ndarray'>
1
(5,)
int32


In [37]:

print(np.zeros(7))  #產生六個元素均為0的一維array
print( )
print(np.zeros((2,7)))  #產生18(3*6)個元素均為0的一維array
print( )
print( )
print(np.zeros((3,3,7)))  #產生36(2*3*6)個元素均為0的一維array

[0. 0. 0. 0. 0. 0. 0.]

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


[[[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]]


In [38]:
a=np.zeros(16)
print(a)
print(a.shape)
b=a.reshape((4,4)) #改變資料的維度為4X4
print(b)
print(b.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(16,)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(4, 4)


### ndarray的進階操作

In [39]:
print(np.arange(11)) #產生一個0~10的一維陣列


[ 0  1  2  3  4  5  6  7  8  9 10]


In [40]:
my_array = np.arange(10)
print(my_array)
print(my_array[0])   
print(my_array[0:5]) #[X:Y] 等於從X開始取Y個

[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]


In [41]:
a = np.array([[0,1,2,3,4],[5,6,7,8,9]])
print(a)
b = np.array([np.arange(0,5),np.arange(5,10)])
print(b)
c = np.array(np.arange(0,10).reshape((2,5)))
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


### 二維ndarray取值

In [42]:
import numpy as np
my_2d_array=np.array(np.arange(0,10).reshape((2,5)))
print(my_2d_array)
print(my_2d_array[0,:]) #第0列的元素
print(my_2d_array[1,]) #第1列的元素
print(my_2d_array[:,0]) #第0欄的元素
print(my_2d_array[1, 1]) #第1列第1欄的元素

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4]
[5 6 7 8 9]
[0 5]
6


## 假設有六個組別"Modern Web", "DevOps", "Cloud", "Big Data", "Security", "自我挑戰組"¶
### 其參加人數分別為55, 9, 20, 12, 6, 78人

In [43]:
# import numpy as np
groups = ["Modern Web", "DevOps", "Cloud", "Big Data", "Security", "自我挑戰組"]
ironman = [55, 9, 20, 12, 6, 78]
groups_array = np.array(groups)
ironman_array = np.array(ironman)
print(groups_array)
print(ironman_array)

['Modern Web' 'DevOps' 'Cloud' 'Big Data' 'Security' '自我挑戰組']
[55  9 20 12  6 78]


### 請問大於10人的組別有哪些?

In [44]:
#用人數去篩選組別
print(ironman_array >= 10)
print(groups_array[ironman_array>=10])

[ True False  True  True False  True]
['Modern Web' 'Cloud' 'Big Data' '自我挑戰組']


### 除了自我挑戰組之外的組別，人數為何?

In [45]:
#用組別去篩選人數
print(groups_array != "自我挑戰組")
print(ironman_array[groups_array != "自我挑戰組"])

[ True  True  True  True  True False]
[55  9 20 12  6]


### ndarray 空值 nan 無限大 inf

In [46]:
nan_array = np.array([55, 9, 12, 14, 6, np.nan])
print(nan_array)

[55.  9. 12. 14.  6. nan]


### 生成10組標準常態分配(平均為0，標準差為1的常態分配)隨機變數

In [47]:
normal_samples = np.random.normal(size=11)
print(normal_samples)

[ 1.11772002 -0.10422083 -0.4321066  -1.00297307 -2.23798186  1.83523894
 -0.21845742 -0.16888127  2.66428956 -0.93720006  0.16599565]


### 生成10組介於0~1之間的隨機變數

In [48]:
uniform_samples = np.random.uniform(size=10)
print(uniform_samples)

[0.1296485  0.36084979 0.57615308 0.30734339 0.56193119 0.28751152
 0.59878314 0.45648859 0.65852675 0.23288045]
